---

# Install extensions with specified database

- name: start postgres
  become: yes
  become_user: postgres
  service: name=postgresql state=started
  vars:
    ansible_ssh_pipelining: true

- name: install extensions
  become: yes
  become_user: postgres
  postgresql_ext: 
    db: "{{ dbname }}"
    name: "{{ item }}"
  with_items:
    - cube
    - earthdistance
    - postgis
  vars:
    ansible_ssh_pipelining: true

- name: install extensions for test_db
  become: yes
  become_user: postgres
  postgresql_ext: 
    db: "test_{{ dbname }}"
    name: "{{ item }}"
  with_items:
    - cube
    - earthdistance
    - postgis
  vars:
    ansible_ssh_pipelining: true
